[build]
  functions = "netlify/functions"
  publish = "."

[[functions]]
  name = "job-email-scheduler"
  schedule = "0 9 * * *"  # Daily at 9 AM UTC

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"